<?php 
include_once("DB_Connection.php");
include_once("Checker.php");
include_once("Word_Checker.php");
include_once("User.php");
include_once("Student.php");
include_once("Teacher.php");
include_once("Task.php");
include_once("Task_Try.php");
include_once("Student_Task.php");
include_once("Discipline.php");
include_once("Test_Data/Test_Student.php");
include_once("Test_Data/Test_Student_Task.php");
include_once("Test_Data/Test_Task.php");
include_once("Test_Data/Test_Teacher.php");
include_once("Test_Data/Test_Discipline.php");
include_once("Test_Data/Test_DB.php");
?>